---Persistence helper for user config overrides.
---Reads/writes `user_config.lua` in the mod root.
local M = {
    __tajsgraph_module = "config_store"
}

local USER_CONFIG_FILENAME = "user_config.lua"

---@param path string|nil
---@return string
local function normalize_path(path)
    return string.gsub(tostring(path or ""), "\\", "/")
end

---@return string
local function get_mod_root()
    local debug_info = debug.getinfo(1, "S")
    if type(debug_info) ~= "table" or type(debug_info.source) ~= "string" then
        return "."
    end

    local source = debug_info.source
    if string.sub(source, 1, 1) == "@" then
        source = string.sub(source, 2)
    end
    source = normalize_path(source)

    local scripts_path = source:match("^(.*)/Scripts/[^/]+%.lua$")
    if type(scripts_path) == "string" and scripts_path ~= "" then
        return scripts_path
    end

    local fallback = source:match("^(.*)/[^/]+%.lua$")
    if type(fallback) == "string" and fallback ~= "" then
        return fallback
    end

    return "."
end

local MOD_ROOT = get_mod_root()
local USER_CONFIG_PATH = normalize_path(MOD_ROOT .. "/" .. USER_CONFIG_FILENAME)

---@param value any
---@return string
local function quote_string(value)
    return string.format("%q", tostring(value))
end

---@param value any
---@return string|nil
local function serialize_value(value)
    local value_type = type(value)
    if value_type == "boolean" then
        return value and "true" or "false"
    end
    if value_type == "number" then
        return tostring(value)
    end
    if value_type == "string" then
        return quote_string(value)
    end
    return nil
end

---@param defaults table
---@return string[]
local function collect_export_keys(defaults)
    local keys = {}
    for key in pairs(defaults) do
        keys[#keys + 1] = key
    end
    keys[#keys + 1] = "spotlight_tune_mode"
    table.sort(keys)
    return keys
end

---@return string
function M.get_user_config_path()
    return USER_CONFIG_PATH
end

---@return table, string|nil
function M.load_user_overrides()
    if type(io) ~= "table" or type(io.open) ~= "function" then
        return {}, "io.open unavailable"
    end
    if type(loadfile) ~= "function" then
        return {}, "loadfile unavailable"
    end

    local probe = io.open(USER_CONFIG_PATH, "r")
    if probe == nil then
        return {}, nil
    end
    probe:close()

    local chunk, load_err = loadfile(USER_CONFIG_PATH)
    if type(chunk) ~= "function" then
        return {}, "failed to load user config: " .. tostring(load_err)
    end

    local ok_exec, data_or_err = pcall(chunk)
    if not ok_exec then
        return {}, "failed to execute user config: " .. tostring(data_or_err)
    end

    if type(data_or_err) ~= "table" then
        return {}, "user config must return a table"
    end

    return data_or_err, nil
end

---@param config table
---@param defaults table
---@return boolean, string|nil
function M.save_user_overrides(config, defaults)
    if type(config) ~= "table" then
        return false, "config must be table"
    end
    if type(defaults) ~= "table" then
        return false, "defaults must be table"
    end
    if type(io) ~= "table" or type(io.open) ~= "function" then
        return false, "io.open unavailable"
    end

    local file, open_err = io.open(USER_CONFIG_PATH, "w")
    if file == nil then
        return false, "failed to open user config for write: " .. tostring(open_err)
    end

    local lines = {
        "-- TajsGraphBM user overrides",
        "-- Generated by tajsgraph.ui.save",
        "return {",
    }

    for _, key in ipairs(collect_export_keys(defaults)) do
        local value = config[key]
        local serialized = serialize_value(value)
        if serialized ~= nil then
            lines[#lines + 1] = string.format("    %s = %s,", key, serialized)
        end
    end

    lines[#lines + 1] = "}"
    lines[#lines + 1] = ""
    file:write(table.concat(lines, "\n"))
    file:close()

    return true, nil
end

return M
