local M = {}

M.CONFIG = {
	include_generic_light_component = true,
	include_rect_light_component = true,

	force_light_movable = true,
	force_light_movable_value = 2,

	megalights_shadow_method = 2, -- default=0, rt=1, vsm=2

	spot_lights_cast_shadows = true,
	point_lights_cast_shadows = true,
	rect_lights_cast_shadows = true,
	generic_lights_cast_shadows = true,
	respect_prepatch_shadow_state = false,

	spotlight_tune_enabled = true,
	spotlight_tune_mode = "multiplier", -- absolute | multiplier
	spotlight_intensity = -1.0,
	spotlight_indirect_lighting_intensity = -1.0,
	spotlight_specular_scale = -1.0,
	spotlight_attenuation_radius = -1.0,
	spotlight_outer_cone_angle = -1.0,
	spotlight_inner_cone_angle = -1.0,
	spotlight_source_radius = -1.0,
	spotlight_soft_source_radius = -1.0,
	spotlight_source_length = -1.0,

	spotlight_intensity_multiplier = 1.50,
	spotlight_indirect_lighting_multiplier = 4.00,
	spotlight_specular_multiplier = 0.90,
	spotlight_attenuation_multiplier = 0.70,
	spotlight_outer_cone_multiplier = 0.90,
	spotlight_inner_cone_multiplier = 0.90,
	spotlight_source_radius_multiplier = 0.90,
	spotlight_soft_source_radius_multiplier = 1.00,
	spotlight_source_length_multiplier = 0.85,

	shadow_tick_ms = 1000,
	cache_refresh_ms = 1000,
	live_shadow_sync = true,

	touch_renderer = true,
	touch_postprocess_volume = true,
	force_ppv_enabled = true,
	force_lumen_methods = true,
	force_lumen_compatibility = true,
	lumen_disable_static_lighting = true,
	lumen_force_no_precomputed_lighting = true,
	lumen_enable_mesh_distance_fields = true,
	lumen_disable_forward_shading = true,
	lumen_gi_method_value = 1,
	lumen_reflection_method_value = 1,
	lumen_scene_detail = 2.8,
	lumen_diffuse_color_boost = 1.5,
	lumen_skylight_leaking = 0.050,
	lumen_max_trace_distance = 200000,

	skylight_runtime_pass = true,
	skylight_force_movable = true,
	skylight_enable_realtime_capture = true,
	skylight_recapture_on_patch = true,
	skylight_recapture_interval_ms = 0,
	skylight_lower_specular_if_needed = false,
	skylight_intensity_multiplier = 1.0,
	skylight_indirect_multiplier = 1.0,

	fog_runtime_pass = true,
	fog_enable_exponential_height_fog = true,
	fog_enable_volumetric_fog = true,
	fog_try_lumen_fog_helpers = true,

	distance_fields_verification = true,
	distance_fields_log_atlas_on_patch = true,
	distance_fields_log_atlas_interval_ms = 0,
	distance_fields_verify_once = false,

	mesh_runtime_pass = true,
	mesh_patch_on_refresh = true,
	mesh_reapply_each_refresh = true,
	mesh_skip_movable = false,
	mesh_include_skeletal_components = true,
	mesh_force_cast_shadow = true,
	mesh_force_dynamic_shadow = true,
	mesh_force_static_shadow = true,
	mesh_force_two_sided_shadow = true,
	mesh_force_distance_field_indirect_shadow = true,
	mesh_force_affect_dynamic_indirect_lighting = true,
	mesh_force_affect_indirect_lighting_while_hidden = true,
	mesh_force_affect_distance_field_lighting = true,
	mesh_force_visible_in_ray_tracing = true,
	mesh_force_visible_in_reflection_captures = true,
	mesh_force_visible_in_realtime_sky_captures = true,
	mesh_force_component_visible = true,
	mesh_force_use_as_occluder = true,
	mesh_force_render_in_main_pass = true,
	mesh_force_render_in_depth_pass = true,
	mesh_force_bounds_scale = false,
	mesh_invalidate_lumen_surface_cache = false,
	mesh_force_render_state_dirty = true,
	mesh_bounds_scale = 1.0,
	mesh_force_never_distance_cull = false,
	mesh_disable_cull_distance_volume = false,
	mesh_force_zero_max_draw_distance = false,
	mesh_force_zero_instance_cull_distances = false,
	mesh_pseudo_thickness_enabled = false,
	mesh_pseudo_thickness_axis = "x",
	mesh_pseudo_thickness_multiplier = 1.0,
	mesh_pseudo_thickness_require_name_filters = true,
	mesh_fix_black_materials = true,
	mesh_force_material_name = "MI_White",
	mesh_force_material_require_name_filters = true,
	mesh_disable_world_position_offset = true,
	mesh_force_generate_mesh_distance_field = true,
	mesh_find_default_query = "wall",
	mesh_find_default_limit = 40,
	mesh_name_filters = {},
	mesh_scope_include_filters = {
		"/game/shopping_mall/maps/shoppingmapfinalplayable",
	},
	mesh_scope_exclude_filters = {
		"/game/enhancedmenu/maps/levelcontainsall",
	},
	mesh_scope_autofix_exclude_names = {
		"levelcontainsall",
	},

	autocomplete_enabled = false,
	autocomplete_dump_path = "D:/Games/BetterMart/BetterMart/Binaries/Win64/UUU_CVarsDump.json",
	autocomplete_max_entries = 10000,
	autocomplete_apply_on_load = false,
	autocomplete_input_ini_path = "C:\\Users\\tajem\\AppData\\Local\\BetterMart\\Saved\\Config\\Windows\\Input.ini",
}

return M
