local M = {}

M.STATE = {
	in_progress = false,
	manager_running = false,

	apply_runs = 0,
	lights_found = 0,
	lights_patched_total = 0,
	lights_patched_last = 0,

	shadow_active = 0,
	shadow_fill_active = 0,
	spot_tuned_last = 0,
	tune_attempted_last = 0,
	tune_changed_last = 0,
	tune_write_fail_last = 0,
	prepatch_captured_last = 0,
	enable_ops_last = 0,
	shadow_ops_last = 0,
	megalights_attempted_last = 0,
	megalights_forced_last = 0,
	megalights_failed_last = 0,

	patched_runtime_last = 0,

	renderer_scanned = 0,
	renderer_enabled = 0,
	compat_renderer_targets = 0,
	compat_static_lighting_disabled = 0,
	compat_distance_fields_enabled = 0,
	compat_forward_shading_disabled = 0,
	compat_world_targets = 0,
	compat_no_precomputed_enabled = 0,

	skylight_found = 0,
	skylight_valid = 0,
	skylight_patched = 0,
	skylight_movable_forced = 0,
	skylight_realtime_enabled = 0,
	skylight_recapture_attempted = 0,
	skylight_recapture_ok = 0,
	skylight_intensity_scaled = 0,
	skylight_indirect_scaled = 0,
	skylight_write_fail = 0,

	fog_actors_found = 0,
	fog_valid = 0,
	fog_enabled = 0,
	fog_volumetric_enabled = 0,
	fog_lumen_fields_seen = 0,
	fog_write_fail = 0,

	df_verify_runs = 0,
	df_atlas_log_requests = 0,
	df_component_scan_count = 0,
	df_components_with_df_flags = 0,
	df_last_verify_time = 0,
	df_last_atlas_log_time = 0,
	df_verify_skipped_reason = "",

	mesh_components_found = 0,
	mesh_components_candidates = 0,
	mesh_foliage_components_found = 0,
	mesh_foliage_components_candidates = 0,
	mesh_skeletal_components_found = 0,
	mesh_skeletal_components_candidates = 0,
	mesh_ism_components_found = 0,
	mesh_ism_components_candidates = 0,
	mesh_hism_components_found = 0,
	mesh_hism_components_candidates = 0,
	mesh_components_patched_total = 0,
	mesh_components_patched_last = 0,
	mesh_write_fail_last = 0,
	mesh_filter_skipped_last = 0,
	mesh_scope_skipped_last = 0,
	mesh_force_apply_ops_last = 0,
	mesh_lumen_cache_invalidations_last = 0,
	mesh_lumen_cache_invalidation_fail_last = 0,
	mesh_render_state_dirty_last = 0,
	mesh_render_state_dirty_fail_last = 0,
	mesh_cull_distance_ops_last = 0,
	mesh_cull_distance_fail_last = 0,
	mesh_bounds_scale_ops_last = 0,
	mesh_bounds_scale_fail_last = 0,
	mesh_pseudo_thickness_ops_last = 0,
	mesh_pseudo_thickness_fail_last = 0,
	mesh_refresh_seq = 0,

	ppv_scanned = 0,
	ppv_enabled = 0,

	skipped_invalid = 0,

	refresh_seq = 0,
	ms_since_refresh = 0,

	last_error = "",

	light_entries = {},
	skylight_scale_baseline = {},
	skylight_last_recapture_ms = {},
	skylight_fail_reasons = {},
	fog_fail_reasons = {},
	df_fail_reasons = {},
	mesh_entries = {},
	df_verified_once = false,

	autocomplete_loaded = false,
	autocomplete_load_error = "",
	autocomplete_parse_count = 0,
	autocomplete_manual_before = 0,
	autocomplete_manual_after = 0,
	autocomplete_applied_count = 0,
	autocomplete_applied = false,
	autocomplete_last_apply_error = "",
	autocomplete_console_marked = 0,
	autocomplete_runtime_before = 0,
	autocomplete_runtime_after = 0,
	autocomplete_runtime_applied_count = 0,
	autocomplete_candidates = {},
	autocomplete_top_results = {},
}

return M
